const chalk = require('chalk');

console.log(chalk.blue('About '));
console.log(chalk.bgRedBright('13.8 billion years '));
console.log(chalk.blue('ago the '));
console.log(chalk.green('Universe, '));
console.log(chalk.blue('that is, '));
console.log(chalk.yellow('time, '));
console.log(chalk.red('matter'));
console.log(chalk.blue(' and '));
console.log(chalk.magentaBright('space'));
console.log(chalk.blue(' began as we currently know it. We label this event the '));
console.log(chalk.yellowBright('Big Bang, '));
console.log(chalk.blue('the entire '));
console.log(chalk.green('Universe '));
console.log(chalk.blue('was condensed into a single point. Its '));
console.log(chalk.bgBlack.bold.whiteBright('density '));
console.log(chalk.blue('and '));
console.log(chalk.redBright('heat '));
console.log(chalk.blue('would be far greater than anything currently in the known '));
console.log(chalk.green('Universe.'));
console.log(chalk.blue('In a faction of a second the '));
console.log(chalk.green('Universe '));
console.log(chalk.blue('went from being '));
console.log(chalk.bgBlack.bold.whiteBright('denser '));
console.log(chalk.blue('than a single atom to larger than a galaxy and has kept expanding ever since. '));
console.log(chalk.whiteBright('Energy '));
console.log(chalk.blue('changed into particles of '));
console.log(chalk.red('matter '));
console.log(chalk.blue('and '));
console.log(chalk.blueBright('antimatter.'));
console.log(chalk.red.bgYellowBright('Protons '));
console.log(chalk.blue('and '));
console.log(chalk.bgBlueBright('neutrons '));
console.log(chalk.blue('began forming while the temperature proceeded to drop over the next'));
console.log(chalk.bgRedBright('3 minutes'));
console.log(chalk.blue('to below '));
console.log(chalk.redBright('1 billion degrees Celsius,'));
console.log(chalk.red.bgYellowBright('hydrogen '));
console.log(chalk.blue('and '));
console.log(chalk.red.bgYellowBright('helium '));
console.log(chalk.blue('were amongst the first on the scene. It took another '));
console.log(chalk.bgRedBright('3,000,000 years '));
console.log(chalk.blue('for the expansion of the '));
console.log(chalk.green('Universe '));
console.log(chalk.blue('to cool to roughly '));
console.log(chalk.redBright('3000 degrees Celsius '));
console.log(chalk.blue('where the '));
console.log(chalk.red.bgYellowBright('atomic nuclei '));
console.log(chalk.blue('could capture '));
console.log(chalk.red.bgYellowBright('electrons '));
console.log(chalk.blue('to begin to form more '));
console.log(chalk.bgBlack.bold.whiteBright('dense  '));
console.log(chalk.blue('atoms.'));